const characters = [
  {
    id: 2,
    name: "Morty Smith",
    species: "Human",
    type: "",
    gender: "Male",
    origin: "Unknown",
    location: "Citadel of Ricks",
    image: "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
  },
  {
    id: 3,
    name: "Summer Smith",
    species: "Human",
    type: "",
    gender: "Female",
    origin: "Earth (Replacement Dimension)",
    location: "Earth (Replacement Dimension)",
    image: "https://rickandmortyapi.com/api/character/avatar/3.jpeg",
  },
  {
    id: 4,
    name: "Beth Smith",
    species: "Human",
    type: "",
    gender: "Female",
    origin: "Earth (Replacement Dimension)",
    location: "Earth (Replacement Dimension)",
    image: "https://rickandmortyapi.com/api/character/avatar/4.jpeg",
  },
  {
    id: 5,
    name: "Jerry Smith",
    species: "Human",
    type: "",
    gender: "Male",
    origin: "Earth (Replacement Dimension)",
    location: "Earth (Replacement Dimension)",
    image: "https://rickandmortyapi.com/api/character/avatar/5.jpeg",
  },{
    id: 6,
    name: "Abadango",
    species: "Alien",
    type: "",
    gender: "Female",
    origin: "Abadango",
    location: "Abadango",
    image: "https://rickandmortyapi.com/api/character/avatar/6.jpeg",
  },{
    id: 7,
    name: "Abradolf Lincler",
    species: "Human",
    type: "Genetic Experiment",
    gender: "Male",
    origin: "Earth (Replacement Dimension)",
    location: "Testicle Monster Dimension",
    image: "https://rickandmortyapi.com/api/character/avatar/7.jpeg",
  },{
    id: 8,
    name: "Adjudicator Rick",
    species: "Human",
    type: "",
    gender: "Male",
    origin: "Unknown",
    location: "Citadel of Ricks",
    image: "https://rickandmortyapi.com/api/character/avatar/8.jpeg",
  },
  {
    id: 9,
    name: "Agency Director",
    species: "Human",
    type: "",
    gender: "Male",
    origin: "Earth (Replacement Dimension)",
    location: "Earth (Replacement Dimension)",
    image: "https://rickandmortyapi.com/api/character/avatar/9.jpeg",
  },
  {
    id: 10,
    name: "Alan Rails",
    species: "Human",
    type: "Superhuman (Ghost trains summoner)",
    gender: "Male",
    origin: "Unknown",
    location: "Worldender`s Lair",
    image: "https://rickandmortyapi.com/api/character/avatar/10.jpeg",
  },{
    id: 11,
    name: "Albert Einstein",
    species: "Human",
    type: "",
    gender: "Male",
    origin: "Earth (C-137)",
    location: "Earth (Replacement Dimension)",
    image: "https://rickandmortyapi.com/api/character/avatar/11.jpeg",
  },{
    id: 12,
    name: "Alexander",
    species: "Human",
    type: "",
    gender: "Male",
    origin: "Earth (C-137)",
    location: "Earth (Replacement Dimension)",
    image: "https://rickandmortyapi.com/api/character/avatar/12.jpeg",
  },{
    id: 13,
    name: "Googah",
    species: "Alien",
    type: "",
    gender: "Unknown",
    origin: "Unknown",
    location: "Earth (Replacement Dimension)",
    image: "https://rickandmortyapi.com/api/character/avatar/13.jpeg",
  },{
    id: 14,
    name: "Alien Morty",
    species: "Alien",
    type: "",
    gender: "Male",
    origin: "Unknown",
    location: "Citadel of Ricks",
    image: "https://rickandmortyapi.com/api/character/avatar/14.jpeg",
  },{
    id: 15,
    name: "Alien Rick",
    species: "Alien",
    type: "",
    gender: "Male",
    origin: "Unknown",
    location: "Citadel of Ricks",
    image: "https://rickandmortyapi.com/api/character/avatar/15.jpeg",
  },
  {
    id: 16,
    name: "Amish Cyborg",
    species: "Alien",
    type: "Parasite",
    gender: "Male",
    origin: "Unknown",
    location: "Earth (Replacement Dimension)",
    image: "https://rickandmortyapi.com/api/character/avatar/16.jpeg",
  },{
    id: 17,
    name: "Annie",
    species: "Human",
    type: "",
    gender: "Female",
    origin: "Earth (C-137)",
    location: "Anatomy Park",
    image: "https://rickandmortyapi.com/api/character/avatar/17.jpeg",
  },{
    id: 18,
    name: "Antenna Morty",
    species: "Human",
    type: "Human with antennae",
    gender: "Male",
    origin: "Unknown",
    location: "Citadel of Ricks",
    image: "https://rickandmortyapi.com/api/character/avatar/18.jpeg",
  },{
    id: 19,
    name: "Antenna Rick",
    species: "Human",
    type: "Human with antennae",
    gender: "Male",
    origin: "Unknown",
    location: "Unknown",
    image: "https://rickandmortyapi.com/api/character/avatar/19.jpeg",
  },{
    id: 20,
    name: "Ants in my eyes Johnson",
    species: "Human",
    type: "Human with ants in his eyes",
    gender: "Male",
    origin: "Unknown",
    location: "Intedimensional Cable",
    image: "https://rickandmortyapi.com/api/character/avatar/20.jpeg",
  },
];

export const Rick = {
  id: 1,
  name: "Rick Sanchez",
  species: "Human",
  type: "",
  gender: "Male",
  origin: "Earth (C-137)",
  location: "Citadel of Ricks",
  image: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
};

export default characters;
