const characters = [
  {
  id: 1,
  name: "Rick Sanchez",
  species: "Human",
  type: "",
  gender: "Male",
  origin: "Earth (C-137)",
  location: "Citadel of Ricks",
  image: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
},
  {
    id: 2,
    name: "Morty Smith",
    species: "Human",
    type: "",
    gender: "Male",
    origin: "Unknown",
    location: "Citadel of Ricks",
    image: "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
  },
  {
    id: 3,
    name: "Summer Smith",
    species: "Human",
    type: "",
    gender: "Female",
    origin: "Earth (Replacement Dimension)",
    location: "Earth (Replacement Dimension)",
    image: "https://rickandmortyapi.com/api/character/avatar/3.jpeg",
  },
  {
    id: 4,
    name: "Beth Smith",
    species: "Human",
    type: "",
    gender: "Female",
    origin: "Earth (Replacement Dimension)",
    location: "Earth (Replacement Dimension)",
    image: "https://rickandmortyapi.com/api/character/avatar/4.jpeg",
  },
  {
    id: 5,
    name: "Jerry Smith",
    species: "Human",
    type: "",
    gender: "Male",
    origin: "Earth (Replacement Dimension)",
    location: "Earth (Replacement Dimension)",
    image: "https://rickandmortyapi.com/api/character/avatar/5.jpeg",
  },{
    id: 242,
    name: "Mr. Meeseeks",
    species: "Humanoid",
    type: "Meeseeks",
    gender: "Female",
    origin: "Mr. Meeseeks Box",
    location: "Earth (Fascist Dimension)",
    image: "https://rickandmortyapi.com/api/character/avatar/242.jpeg",
  },{
    id: 7,
    name: "Abradolf Lincler",
    species: "Human",
    type: "Genetic Experiment",
    gender: "Male",
    origin: "Earth (Replacement Dimension)",
    location: "Testicle Monster Dimension",
    image: "https://rickandmortyapi.com/api/character/avatar/7.jpeg",
  },{
    id: 8,
    name: "Adjudicator Rick",
    species: "Human",
    type: "",
    gender: "Male",
    origin: "Unknown",
    location: "Citadel of Ricks",
    image: "https://rickandmortyapi.com/api/character/avatar/8.jpeg",
  },
  {
    id: 9,
    name: "Agency Director",
    species: "Human",
    type: "",
    gender: "Male",
    origin: "Earth (Replacement Dimension)",
    location: "Earth (Replacement Dimension)",
    image: "https://rickandmortyapi.com/api/character/avatar/9.jpeg",
  },
  {
    id: 243,
    name: "Mr. Needful",
    species: "Humanoid",
    type: "The Devil",
    gender: "Male",
    origin: "Unknown",
    location: "Earth (Replacement Dimension)",
    image: "https://rickandmortyapi.com/api/character/avatar/243.jpeg",
  },{
    id: 250,
    name: "Mrs. Sullivan",
    species: "Human",
    type: "Cat controlled dead lady",
    gender: "Female",
    origin: "Earth (C-500A)",
    location: "Interdimensional Cable",
    image: "https://rickandmortyapi.com/api/character/avatar/250.jpeg",
  },{
    id: 28,
    name: "Atila Starwar",
    species: "Human",
    type: "",
    gender: "Male",
    origin: "Unknown",
    location: "Interdimensional Cable",
    image: "https://rickandmortyapi.com/api/character/avatar/28.jpeg",
  },{
    id: 81,
    name: "Crocubot",
    species: "Animal",
    type: "Robot-Crocodile Hybrid",
    gender: "Unknown",
    origin: "Worldender`s Lair",
    location: "Earth (Replacement Dimension)",
    image: "https://rickandmortyapi.com/api/character/avatar/81.jpeg",
  },{
    id: 33,
    name: "Beebo",
    species: "Alien",
    type: "",
    gender: "Male",
    origin: "Venzenulon 7",
    location: "Venzenulon 7",
    image: "https://rickandmortyapi.com/api/character/avatar/33.jpeg",
  },{
    id: 50,
    name: "Blim Blam",
    species: "Alien",
    type: "Korblock",
    gender: "Male",
    origin: "Unknown",
    location: "Earth (Replacement Dimension",
    image: "https://rickandmortyapi.com/api/character/avatar/50.jpeg",
  },
  {
    id: 192,
    name: "King Flippy Nips",
    species: "Alien",
    type: "Plutonian",
    gender: "Male",
    origin: "Pluto",
    location: "Pluto",
    image: "https://rickandmortyapi.com/api/character/avatar/192.jpeg",
  },{
    id: 57,
    name: "Borpocian",
    species: "Alien",
    type: "Elephant Person",
    gender: "Male",
    origin: "Unknown",
    location: "Unknown",
    image: "https://rickandmortyapi.com/api/character/avatar/57.jpeg",
  },{
    id: 63,
    name: "Centaur",
    species: "Mythological Creature",
    type: "Centaur",
    gender: "Male",
    origin: "Unknown",
    location: "Mr. Goldenfold`s dream",
    image: "https://rickandmortyapi.com/api/character/avatar/63.jpeg",
  },{
    id: 68,
    name: "Colossus",
    species: "Human",
    type: "",
    gender: "Male",
    origin: "Post-Apocalyptic Earth",
    location: "Post-Apocalyptic Earth",
    image: "https://rickandmortyapi.com/api/character/avatar/68.jpeg",
  },{
    id: 70,
    name: "Concerto",
    species: "Humanoid",
    type: "",
    gender: "Male",
    origin: "Unknown",
    location: "Unknown",
    image: "https://rickandmortyapi.com/api/character/avatar/70.jpeg",
  },
];

// export const Rick = {
//   id: 1,
//   name: "Rick Sanchez",
//   species: "Human",
//   type: "",
//   gender: "Male",
//   origin: "Earth (C-137)",
//   location: "Citadel of Ricks",
//   image: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
// };

export default characters;
